### ISSUE TITLE
Question: SNV calling in low tumor content setting

### ISSUE THREAD

**Issue by GMFranceschini** [guoweilong/cgmaptools#61]
Dear cgmaptools developer,
I wondered if you ever tested your tool in samples with low SNV frequency. 
Working on cancer-related samples, I often encounter cases where the fraction of tumor DNA is even below 50%; do you know how the SNV calling procedure you implemented performs in that setting?
Thank you

**Comment by guoweilong** [comment]
The SNV calling in CGmapTools is developed for normal tissues, which would not be directly used for the senario when tthe umor DNA is below 50% or even lower.


Considering the SNP calling is an even harder problem when working on the the heterogenous tumor tissues, I would suggest you to perform high-coverage DNA sequencing for SNV calling, rather than using BS-seq data.



Weilong





At 2022-10-28 15:39:22, "Gian M. Franceschini" ***@***.***> wrote:

Dear cgmaptools developer,
I wondered if you ever tested your tool in samples with low SNV frequency.
Working on cancer-related samples, I often encounter cases where the fraction of tumor DNA is even below 50%; do you know how the SNV calling procedure you implemented performs in that setting?
Thank you

**Comment by GMFranceschini** [comment]
Thank you for the help, closing the issue
